name:                decaf
version:             0.1.0.0
github:              "zhangjunphy/decaf"
license:             MIT
license-file:        LICENSE
author:              "zj"
maintainer:          "zhangjunphy[at]gmail[dot]com"
copyright:           "MIT"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zhangjunphy/decaf#README.md>

default-extensions:
- DataKinds
- DuplicateRecordFields
- DeriveGeneric
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- OverloadedStrings
- OverloadedLabels
- DeriveFunctor
- TupleSections

dependencies:
- base >=4.7 && <5
- array ==0.5.*
- split ==0.2.*
- transformers ==0.5.*
- containers >=0.4
- mtl
- bytestring ==0.11.*
- text ==2.0.*
- formatting ==7.2.*
- lens ==5.2.*
- generic-lens ==2.2.*

library:
  source-dirs:
    - src

  build-tools:
    - alex ==3.3.*
    - happy ==1.20.*

executables:
  decafc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf

tests:
  decaf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - decaf
    - hspec
