* L2
** 1. What is the main job of a compiler?
   Transform one kind of program representation into another.
***  What is the input to a compiler?
    High-level programming language.
*** What does the compiler produce as output?
    Low-level assembly instructions.


* L3
** 1
*** Q:
Consider the language of binary strings defined by the following regular expression:

=(10)∗01(10)∗(0|1)=

Which of these strings are accepted by this expression? (Circle all that apply, if any).
#+begin_example
10011
0110101
01
1010010
10011001
#+end_example
*** A:
#+begin_example
10011
0110101
1010010
#+end_example

** 2
*** Q:
Give a regular expression which accepts the language of all binary
strings which end in 1 and whose length is a positive multiple of 3.
*** A:
=((0|1){3})*(0|1){2}1=

** 3
*** Q:
Does the regular expression

=[+|−](0|1|...|9)∗[.](0|1|...|9)∗=

recognize the language of decimal numbers? Why or why not?
*** A:
Not strictly. It can match all decimal numbers. But it also accepts =-.= or =000=,
which are generally not considered decimal numbers.
